server:
  port: 8084

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:paymentdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

springdoc:
  packages-to-scan: com.rak.payment.controller  # Adjust if your controllers are in a different package
  paths-to-match: /api/**
